PRAGMA foreign_keys = ON;


CREATE TABLE Country
(
    country_id   INTEGER PRIMARY KEY AUTOINCREMENT,
    country_name VARCHAR(100) NOT NULL,
    UNIQUE (country_name)
);

CREATE TABLE Contributor
(
    contributor_id   INTEGER PRIMARY KEY AUTOINCREMENT,
    contributor_name VARCHAR(150) NOT NULL
);

CREATE TABLE ContributorType
(
    contributor_type_id INTEGER PRIMARY KEY AUTOINCREMENT,
    type_name           VARCHAR(50) NOT NULL,
    UNIQUE (type_name)
);

CREATE TABLE ContributorNationality
(
    contributor_nationality_id INTEGER PRIMARY KEY AUTOINCREMENT,
    contributor_id             INTEGER NOT NULL,
    country_id                 INTEGER NOT NULL,

    CONSTRAINT fk_contributornationality_contributor
        FOREIGN KEY (contributor_id) REFERENCES Contributor (contributor_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE,
    CONSTRAINT fk_contributornationality_country
        FOREIGN KEY (country_id) REFERENCES Country (country_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE
);

CREATE TABLE Genre
(
    genre_id   INTEGER PRIMARY KEY AUTOINCREMENT,
    genre_name VARCHAR(100) NOT NULL,
    UNIQUE (genre_name)
);

CREATE TABLE Book
(
    book_id          INTEGER PRIMARY KEY AUTOINCREMENT,
    book_name        VARCHAR(255) NOT NULL,
    book_description TEXT         NULL
);

CREATE TABLE BookContributor
(
    book_contributor_id      INTEGER PRIMARY KEY AUTOINCREMENT,
    book_id                  INTEGER      NOT NULL,
    contributor_id           INTEGER      NOT NULL,
    contributor_type_id      INTEGER      NOT NULL,
    contribution_description VARCHAR(500) NULL,
    UNIQUE (book_id, contributor_id, contributor_type_id),
    CONSTRAINT fk_bookcontributor_book
        FOREIGN KEY (book_id) REFERENCES Book (book_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE,
    CONSTRAINT fk_bookcontributor_contributor
        FOREIGN KEY (contributor_id) REFERENCES Contributor (contributor_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE,
    CONSTRAINT fk_bookcontributor_contributortype
        FOREIGN KEY (contributor_type_id) REFERENCES ContributorType (contributor_type_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE
);



CREATE TABLE BookGenre
(
    book_genre_id INTEGER PRIMARY KEY AUTOINCREMENT,
    book_id       INTEGER NOT NULL,
    genre_id      INTEGER NOT NULL,
    UNIQUE (book_id, genre_id),
    CONSTRAINT fk_bookgenre_book
        FOREIGN KEY (book_id) REFERENCES Book (book_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE,
    CONSTRAINT fk_bookgenre_genre
        FOREIGN KEY (genre_id) REFERENCES Genre (genre_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE
);

INSERT INTO Country (country_name)
VALUES ('United Kingdom'),
       ('United States'),
       ('Colombia'),
       ('Japan'),
       ('Nigeria'),
       ('France'),
       ('Russia'),
       ('Germany'),
       ('Chile'),
       ('Canada'),
       ('India'),
       ('Ireland'),
       ('South Africa'),
       ('Italy'),
       ('Spain'),
       ('Egypt'),
       ('Brazil'),
       ('China'),
       ('Turkey'),
       ('Mexico'),
       ('Australia');

INSERT INTO ContributorType (type_name)
VALUES ('Author'),
       ('Translator'),
       ('Editor'),
       ('Illustrator'),
       ('Introduction'),
       ('Compiler');
INSERT INTO Contributor (contributor_name)
VALUES ('George Orwell'),
       ('Ernest Hemingway'),
       ('Gabriel Garcia Marquez'),
       ('Haruki Murakami'),
       ('Chimamanda Ngozi Adichie'),
       ('Albert Camus'),
       ('Fyodor Dostoevsky'),
       ('Franz Kafka'),
       ('Isabel Allende'),
       ('Margaret Atwood'),
       ('Arundhati Roy'),
       ('James Joyce'),
       ('J.M. Coetzee'),
       ('Italo Calvino'),
       ('Carlos Ruiz Zafon'),
       ('Naguib Mahfouz'),
       ('Jorge Amado'),
       ('Lu Xun'),
       ('Orhan Pamuk'),
       ('Juan Rulfo'),
       ('Virginia Woolf'),
       ('F. Scott Fitzgerald'),
       ('Kazuo Ishiguro'),
       ('Wole Soyinka'),
       ('Victor Hugo'),
       ('Leo Tolstoy'),
       ('Thomas Mann'),
       ('Toni Morrison'),
       ('Salman Rushdie'),
       ('Agatha Christie');

INSERT INTO ContributorNationality (contributor_id, country_id)
VALUES (1, 1),
       (2, 2),
       (3, 3),
       (4, 4),
       (5, 5),
       (6, 6),
       (7, 7),
       (8, 8),
       (9, 9),
       (9, 2),
       (10, 10),
       (11, 11),
       (12, 12),
       (13, 13),
       (13, 21),
       (14, 14),
       (15, 15),
       (16, 16),
       (17, 17),
       (18, 18),
       (19, 19),
       (20, 20),
       (21, 1),
       (22, 2),
       (23, 4),
       (23, 1),
       (24, 5),
       (25, 6),
       (26, 7),
       (27, 8),
       (28, 2),
       (29, 11),
       (30, 1);
INSERT INTO Genre (genre_name)
VALUES ('Dystopian Fiction'),
       ('Literary Fiction'),
       ('Magical Realism'),
       ('Historical Fiction'),
       ('Short Story'),
       ('Science Fiction'),
       ('Fantasy'),
       ('Mystery'),
       ('Romance'),
       ('Horror'),
       ('Crime Fiction'),
       ('Adventure'),
       ('Satire'),
       ('Biography'),
       ('Poetry');

INSERT INTO Book (book_name, book_description)
VALUES ('1984', 'A dystopian novel set in a totalitarian society under constant surveillance.'),
       ('Animal Farm', 'A satirical allegory of the Russian Revolution told through farm animals.'),
       ('The Old Man and the Sea', 'A short novel about an aging fisherman and his struggle with a giant marlin.'),
       ('A Farewell to Arms', 'A novel set during World War I following an American ambulance driver.'),
       ('One Hundred Years of Solitude',
        'A multi-generational story of the Buendia family in the fictional town of Macondo.'),
       ('Love in the Time of Cholera', 'A tale of love that endures across five decades.'),
       ('Norwegian Wood', 'A nostalgic story of loss and burgeoning sexuality set in 1960s Tokyo.'),
       ('Kafka on the Shore', 'A surreal narrative weaving together two seemingly unrelated stories.'),
       ('Half of a Yellow Sun', 'A novel set during the Nigerian Civil War, following several intertwined lives.'),
       ('Americanah', 'A story exploring race, identity, and love across continents.'),
       ('The Stranger', 'A novel exploring absurdism through the eyes of an indifferent narrator.'),
       ('The Plague', 'An allegorical novel about a plague sweeping through a North African town.'),
       ('Crime and Punishment', 'A psychological exploration of guilt following a murder in St. Petersburg.'),
       ('The Brothers Karamazov', 'A philosophical novel about faith, doubt, and family conflict.'),
       ('The Trial', 'A man is arrested and prosecuted by a remote, inaccessible authority.'),
       ('The Metamorphosis', 'A travelling salesman wakes to find himself transformed into a giant insect.'),
       ('The House of the Spirits', 'A multi-generational saga blending politics and the supernatural.'),
       ('Eva Luna', 'The story of a woman who becomes a gifted storyteller.'),
       ('The Handmaid''s Tale', 'A dystopian novel set in a totalitarian society that subjugates women.'),
       ('Oryx and Crake', 'A speculative novel exploring bioengineering and societal collapse.'),
       ('The God of Small Things', 'A story of forbidden love and family tragedy in Kerala, India.'),
       ('Ulysses', 'A modernist novel following a day in the life of Leopold Bloom in Dublin.'),
       ('Dubliners', 'A collection of short stories depicting middle-class life in early 1900s Dublin.'),
       ('Disgrace', 'A novel exploring morality and redemption in post-apartheid South Africa.'),
       ('Invisible Cities', 'A series of prose poems describing fantastical cities to an emperor.'),
       ('The Shadow of the Wind', 'A young boy discovers a mysterious book that changes his life.'),
       ('Palace Walk', 'A family saga set in Cairo during British occupation.'),
       ('Gabriela, Clove and Cinnamon', 'A romance set in a small Brazilian coastal town.'),
       ('Diary of a Madman', 'A short story satirizing traditional Chinese society.'),
       ('My Name Is Red', 'A murder mystery set among miniaturist painters in the Ottoman court.'),
       ('Pedro Paramo', 'A man travels to a ghost town to find the father he never knew.'),
       ('Mrs Dalloway', 'A single day in the life of a woman preparing for a party in London.'),
       ('To the Lighthouse', 'A meditative novel exploring family and the passage of time.'),
       ('The Great Gatsby', 'A novel of wealth, obsession, and the American Dream in the Jazz Age.'),
       ('Tender Is the Night', 'A story of a psychiatrist and his wife unravelling on the French Riviera.'),
       ('Never Let Me Go', 'A haunting story of childhood friends confronting a dark shared fate.'),
       ('The Remains of the Day', 'A butler reflects on a life of duty and missed opportunity.'),
       ('Death and the King''s Horseman', 'A play exploring colonial interference in Yoruba tradition.'),
       ('Les Miserables', 'An epic tale of redemption set against the backdrop of 19th-century France.'),
       ('The Hunchback of Notre-Dame', 'A tragic tale centred on a bell-ringer in medieval Paris.'),
       ('War and Peace', 'An epic chronicle of Russian society during the Napoleonic Wars.'),
       ('Anna Karenina', 'A tragic story of adultery and societal judgement in Imperial Russia.'),
       ('Death in Venice', 'A novella exploring obsession and beauty in early 20th-century Venice.'),
       ('Beloved', 'A former slave is haunted by the ghost of her deceased daughter.'),
       ('Song of Solomon', 'A novel following a man''s search for identity and heritage.'),
       ('Midnight''s Children', 'A story of children born at the moment of India''s independence.'),
       ('The Satanic Verses', 'A novel exploring identity and faith through magical realist storytelling.'),
       ('Murder on the Orient Express', 'A detective investigates a murder aboard a snowbound train.'),
       ('And Then There Were None', 'Ten strangers are lured to an island and killed one by one.');

INSERT INTO BookContributor (book_id, contributor_id, contributor_type_id, contribution_description)
VALUES (1, 1, 1, 'Sole author'),
       (2, 1, 1, 'Sole author'),
       (3, 2, 1, 'Sole author'),
       (4, 2, 1, 'Sole author'),
       (5, 3, 1, 'Sole author'),
       (6, 3, 1, 'Sole author'),
       (7, 4, 1, 'Sole author'),
       (8, 4, 1, 'Sole author'),
       (9, 5, 1, 'Sole author'),
       (10, 5, 1, 'Sole author'),
       (11, 6, 1, 'Sole author'),
       (12, 6, 1, 'Sole author'),
       (13, 7, 1, 'Sole author'),
       (14, 7, 1, 'Sole author'),
       (15, 8, 1, 'Sole author'),
       (16, 8, 1, 'Sole author'),
       (17, 9, 1, 'Sole author'),
       (18, 9, 1, 'Sole author'),
       (19, 10, 1, 'Sole author'),
       (20, 10, 1, 'Sole author'),
       (21, 11, 1, 'Sole author'),
       (22, 12, 1, 'Sole author'),
       (23, 12, 1, 'Sole author'),
       (24, 13, 1, 'Sole author'),
       (25, 14, 1, 'Sole author'),
       (26, 15, 1, 'Sole author'),
       (27, 16, 1, 'Sole author'),
       (28, 17, 1, 'Sole author'),
       (29, 18, 1, 'Sole author'),
       (30, 19, 1, 'Sole author'),
       (31, 20, 1, 'Sole author'),
       (32, 21, 1, 'Sole author'),
       (33, 21, 1, 'Sole author'),
       (34, 22, 1, 'Sole author'),
       (35, 22, 1, 'Sole author'),
       (36, 23, 1, 'Sole author'),
       (37, 23, 1, 'Sole author'),
       (38, 24, 1, 'Sole author'),
       (39, 25, 1, 'Sole author'),
       (40, 25, 1, 'Sole author'),
       (41, 26, 1, 'Sole author'),
       (42, 26, 1, 'Sole author'),
       (43, 27, 1, 'Sole author'),
       (44, 28, 1, 'Sole author'),
       (45, 28, 1, 'Sole author'),
       (46, 29, 1, 'Sole author'),
       (47, 29, 1, 'Sole author'),
       (48, 30, 1, 'Sole author'),
       (49, 30, 1, 'Sole author');

INSERT INTO BookGenre (book_id, genre_id)
VALUES (1, 1),
       (1, 2),
       (2, 13),
       (2, 1),
       (3, 2),
       (3, 5),
       (4, 4),
       (4, 2),
       (5, 3),
       (5, 4),
       (6, 9),
       (6, 3),
       (7, 2),
       (7, 9),
       (8, 3),
       (8, 7),
       (9, 4),
       (9, 2),
       (10, 2),
       (10, 9),
       (11, 2),
       (11, 8),
       (12, 2),
       (12, 4),
       (13, 11),
       (13, 2),
       (14, 2),
       (15, 1),
       (15, 8),
       (16, 5),
       (16, 7),
       (17, 3),
       (17, 4),
       (18, 3),
       (18, 9),
       (19, 1),
       (19, 6),
       (20, 6),
       (20, 1),
       (21, 2),
       (22, 2),
       (23, 5),
       (23, 2),
       (24, 2),
       (25, 7),
       (25, 15),
       (26, 8),
       (26, 4),
       (27, 4),
       (28, 9),
       (28, 4),
       (29, 5),
       (29, 13),
       (30, 8),
       (30, 4),
       (31, 3),
       (32, 2),
       (33, 2),
       (34, 2),
       (34, 9),
       (35, 2),
       (36, 6),
       (36, 2),
       (37, 2),
       (37, 4),
       (38, 4),
       (39, 4),
       (39, 12),
       (40, 4),
       (40, 9),
       (41, 4),
       (41, 2),
       (42, 9),
       (42, 2),
       (43, 2),
       (43, 5),
       (44, 4),
       (44, 2),
       (45, 2),
       (46, 3),
       (46, 4),
       (47, 3),
       (47, 7),
       (48, 8),
       (48, 11),
       (49, 8),
       (49, 11);

INSERT INTO Country (country_name)
VALUES ('Argentina'),
       ('Peru'),
       ('Czech Republic'),
       ('Poland'),
       ('Portugal'),
       ('Sweden'),
       ('Norway'),
       ('Denmark'),
       ('Greece'),
       ('Austria'),
       ('Hungary'),
       ('Iceland'),
       ('Israel'),
       ('Vietnam'),
       ('South Korea'),
       ('Indonesia'),
       ('Kenya'),
       ('Zimbabwe'),
       ('Trinidad and Tobago'),
       ('New Zealand'),
       ('Pakistan'),
       ('Afghanistan'),
       ('Guatemala'),
       ('Sri Lanka'),
       ('Iran');

INSERT INTO Contributor (contributor_name)
VALUES ('Jorge Luis Borges'),
       ('Julio Cortazar'),
       ('Mario Vargas Llosa'),
       ('Pablo Neruda'),
       ('Milan Kundera'),
       ('Bohumil Hrabal'),
       ('Wislawa Szymborska'),
       ('Czeslaw Milosz'),
       ('Jose Saramago'),
       ('Fernando Pessoa'),
       ('Astrid Lindgren'),
       ('Stieg Larsson'),
       ('Henrik Ibsen'),
       ('Knut Hamsun'),
       ('Hans Christian Andersen'),
       ('Karen Blixen'),
       ('Nikos Kazantzakis'),
       ('Stefan Zweig'),
       ('Imre Kertesz'),
       ('Sandor Marai'),
       ('Halldor Laxness'),
       ('Amos Oz'),
       ('David Grossman'),
       ('Nguyen Du'),
       ('Han Kang'),
       ('Pramoedya Ananta Toer'),
       ('Ngugi wa Thiong''o'),
       ('Tsitsi Dangarembga'),
       ('V.S. Naipaul'),
       ('Katherine Mansfield'),
       ('Bapsi Sidhwa'),
       ('Khaled Hosseini'),
       ('Miguel Angel Asturias'),
       ('Michael Ondaatje'),
       ('Sadegh Hedayat'),
       ('Herman Melville'),
       ('Mark Twain'),
       ('Nathaniel Hawthorne'),
       ('John Steinbeck'),
       ('William Faulkner'),
       ('Harper Lee'),
       ('Kurt Vonnegut'),
       ('Philip Roth'),
       ('Ray Bradbury'),
       ('Ursula K. Le Guin'),
       ('Charles Dickens'),
       ('Jane Austen'),
       ('Charlotte Bronte'),
       ('Emily Bronte'),
       ('Thomas Hardy'),
       ('Oscar Wilde'),
       ('J.R.R. Tolkien'),
       ('C.S. Lewis'),
       ('Aldous Huxley'),
       ('Doris Lessing'),
       ('Ian McEwan'),
       ('Zadie Smith'),
       ('Hilary Mantel');
INSERT INTO ContributorNationality (contributor_id, country_id)
VALUES (31, 22),
       (32, 22),
       (33, 23),
       (33, 15),
       (34, 9),
       (35, 24),
       (35, 6),
       (36, 24),
       (37, 25),
       (38, 25),
       (38, 2),
       (39, 26),
       (40, 26),
       (41, 27),
       (42, 27),
       (43, 28),
       (44, 28),
       (45, 29),
       (46, 29),
       (47, 30),
       (48, 31),
       (49, 32),
       (50, 32),
       (51, 33),
       (52, 34),
       (53, 34),
       (54, 35),
       (55, 36),
       (56, 37),
       (57, 38),
       (58, 39),
       (59, 40),
       (59, 1),
       (60, 41),
       (61, 42),
       (61, 2),
       (62, 43),
       (62, 2),
       (63, 44),
       (64, 45),
       (64, 10),
       (65, 46),
       (66, 2),
       (67, 2),
       (68, 2),
       (69, 2),
       (70, 2),
       (71, 2),
       (72, 2),
       (73, 2),
       (74, 2),
       (75, 2),
       (76, 1),
       (77, 1),
       (78, 1),
       (79, 1),
       (80, 1),
       (81, 12),
       (82, 1),
       (83, 1),
       (84, 1),
       (85, 1),
       (85, 39),
       (86, 1),
       (87, 1),
       (88, 1);
INSERT INTO Genre (genre_name)
VALUES ('Children''s Literature'),
       ('Gothic Fiction'),
       ('War Fiction'),
       ('Epic Poetry'),
       ('Memoir'),
       ('Essay'),
       ('Drama');
INSERT INTO Book (book_name, book_description)
VALUES ('Ficciones',
        'A collection of interlinked short stories exploring labyrinths, infinite libraries, and philosophical paradoxes.'),
       ('The Aleph',
        'A collection of short stories centred on a point in space that contains all other points in the universe.'),
       ('Hopscotch',
        'An experimental novel that can be read in multiple sequences, following an Argentine expatriate in Paris and Buenos Aires.'),
       ('The Time of the Hero',
        'A novel exploring corruption and violence among cadets at a military academy in Lima.'),
       ('The Feast of the Goat', 'A novel examining the dictatorship of Rafael Trujillo in the Dominican Republic.'),
       ('Twenty Love Poems and a Song of Despair', 'An early collection of romantic and melancholic poetry.'),
       ('Canto General', 'An epic poetry collection tracing the history and geography of Latin America.'),
       ('The Unbearable Lightness of Being',
        'A novel exploring love, freedom, and fate against the backdrop of the 1968 Prague Spring.'),
       ('The Book of Laughter and Forgetting',
        'A novel blending fiction and essay to explore memory and political oppression in Czechoslovakia.'),
       ('Closely Watched Trains',
        'A novel set at a rural railway station during the German occupation of Czechoslovakia.'),
       ('View with a Grain of Sand', 'A collection of poems reflecting on everyday life and existence.'),
       ('The Captive Mind', 'An essay examining the appeal of totalitarianism to intellectuals under communist rule.'),
       ('Blindness', 'A novel depicting the breakdown of society after an epidemic of sudden blindness.'),
       ('The Gospel According to Jesus Christ', 'A reimagining of the life of Jesus from a humanist perspective.'),
       ('The Book of Disquiet', 'A fragmentary work presenting the reflections of a Lisbon office worker.'),
       ('Pippi Longstocking', 'A children''s story about an unconventional and independent young girl.'),
       ('The Girl with the Dragon Tattoo',
        'A crime novel following a journalist and a hacker investigating a decades-old disappearance.'),
       ('A Doll''s House',
        'A play examining the constraints of marriage and gender roles in nineteenth-century Norway.'),
       ('Hunger', 'A novel following a struggling writer''s descent into poverty and starvation in Christiania.'),
       ('The Little Mermaid', 'A fairy tale about a young mermaid who longs for a human soul.'),
       ('Out of Africa', 'A memoir recounting the author''s years running a coffee farm in Kenya.'),
       ('Zorba the Greek', 'A novel following the friendship between an intellectual narrator and a vibrant labourer.'),
       ('The Last Temptation of Christ',
        'A novel reimagining the inner struggles of Jesus between the human and the divine.'),
       ('Chess Story', 'A novella exploring obsession through a chess match aboard an ocean liner.'),
       ('Fatelessness', 'A novel following a teenage boy''s experience in Nazi concentration camps.'),
       ('Embers', 'A novel centred on a reunion between two ageing friends and a long-held betrayal.'),
       ('Independent People', 'A novel following an Icelandic sheep farmer''s struggle for self-sufficiency.'),
       ('A Tale of Love and Darkness',
        'A memoir recounting the author''s childhood in Jerusalem before and after Israeli independence.'),
       ('To the End of the Land',
        'A novel following a mother who sets off on a journey to avoid news of her son at war.'),
       ('The Tale of Kieu', 'An epic narrative poem recounting the trials of a virtuous young woman.'),
       ('The Vegetarian', 'A novel following a woman''s decision to stop eating meat and its effect on her family.'),
       ('This Earth of Mankind', 'A novel set in colonial-era Java, following a young man''s coming of age.'),
       ('Petals of Blood', 'A novel examining corruption and inequality in post-independence Kenya.'),
       ('Nervous Conditions', 'A novel following a young girl''s education and identity in colonial Rhodesia.'),
       ('A House for Mr Biswas',
        'A novel following a man''s lifelong pursuit of independence and home ownership in Trinidad.'),
       ('The Garden Party',
        'A collection of short stories examining class and social convention in New Zealand and England.'),
       ('Cracking India', 'A novel viewing the partition of India through the eyes of a young girl in Lahore.'),
       ('The Kite Runner', 'A novel following a friendship shaped by betrayal and redemption in Afghanistan.'),
       ('A Thousand Splendid Suns',
        'A novel following the intertwined lives of two women in Afghanistan across decades of conflict.'),
       ('Men of Maize', 'A novel blending myth and reality in the lives of Guatemala''s indigenous communities.'),
       ('The English Patient',
        'A novel following four damaged lives converging in an Italian villa near the end of the Second World War.'),
       ('The Blind Owl', 'A surreal novella exploring isolation and obsession through a narrator''s fevered visions.'),
       ('Moby-Dick', 'A novel following a whaling voyage and one captain''s obsessive pursuit of a white whale.'),
       ('Adventures of Huckleberry Finn',
        'A novel following a boy''s journey down the Mississippi River with an escaped enslaved man.'),
       ('The Adventures of Tom Sawyer',
        'A novel following the escapades of a mischievous boy in a Mississippi River town.'),
       ('The Scarlet Letter', 'A novel examining sin and redemption in Puritan New England.'),
       ('The Grapes of Wrath',
        'A novel following a family''s migration from the Dust Bowl to California during the Great Depression.'),
       ('Of Mice and Men', 'A novella following two migrant workers and their dream of owning land.'),
       ('The Sound and the Fury',
        'A novel told through multiple perspectives tracing the decline of a Southern family.'),
       ('As I Lay Dying',
        'A novel following a family''s journey to bury their mother, told through shifting narrators.'),
       ('To Kill a Mockingbird',
        'A novel examining racial injustice in a small Southern town through a child''s eyes.'),
       ('Slaughterhouse-Five', 'A novel blending science fiction and war narrative to depict the bombing of Dresden.'),
       ('Cat''s Cradle', 'A satirical novel examining science, religion, and the end of the world.'),
       ('American Pastoral', 'A novel examining the unravelling of an American family amid social upheaval.'),
       ('Fahrenheit 451', 'A novel depicting a future society in which books are banned and burned.'),
       ('The Martian Chronicles', 'A collection of linked stories chronicling the human colonisation of Mars.'),
       ('The Left Hand of Darkness', 'A novel exploring gender and diplomacy on a distant, ice-bound planet.'),
       ('A Wizard of Earthsea',
        'A novel following a young wizard''s education and confrontation with a shadow of his own making.'),
       ('Oliver Twist', 'A novel following an orphan''s experiences among London''s criminal underclass.'),
       ('Great Expectations',
        'A novel following an orphan''s rise in society and the mysterious benefactor who funds it.'),
       ('A Tale of Two Cities', 'A novel set in London and Paris during the years leading to the French Revolution.'),
       ('Pride and Prejudice', 'A novel examining marriage, class, and first impressions in Regency England.'),
       ('Sense and Sensibility', 'A novel following two sisters navigating love and financial hardship.'),
       ('Jane Eyre', 'A novel following an orphaned governess''s pursuit of independence and love.'),
       ('Wuthering Heights',
        'A novel depicting a turbulent, all-consuming love across two generations on the Yorkshire moors.'),
       ('Tess of the d''Urbervilles',
        'A novel following a young woman''s suffering under rigid social and moral codes.'),
       ('The Picture of Dorian Gray',
        'A novel following a man whose portrait bears the marks of his moral decay while he remains unchanged.'),
       ('The Hobbit', 'A fantasy novel following a reluctant hobbit''s journey to help reclaim a dwarven kingdom.'),
       ('The Lord of the Rings',
        'An epic fantasy following the quest to destroy a powerful ring and defeat a dark lord.'),
       ('The Lion, the Witch and the Wardrobe',
        'A fantasy novel following four children who discover a magical kingdom through a wardrobe.'),
       ('Brave New World',
        'A novel depicting a future society engineered for stability through genetic design and conditioning.'),
       ('The Golden Notebook', 'A novel exploring a writer''s fragmented life through four separate notebooks.'),
       ('Atonement',
        'A novel following the lasting consequences of a childhood misunderstanding across wartime Britain.'),
       ('White Teeth', 'A novel following two families across generations in multicultural London.'),
       ('Wolf Hall', 'A novel following the rise of Thomas Cromwell in the court of Henry VIII.');

INSERT INTO BookContributor (book_id, contributor_id, contributor_type_id, contribution_description)
VALUES (50, 31, 1, 'Sole author'),
       (51, 31, 1, 'Sole author'),
       (52, 32, 1, 'Sole author'),
       (53, 33, 1, 'Sole author'),
       (54, 33, 1, 'Sole author'),
       (55, 34, 1, 'Sole author'),
       (56, 34, 1, 'Sole author'),
       (57, 35, 1, 'Sole author'),
       (58, 35, 1, 'Sole author'),
       (59, 36, 1, 'Sole author'),
       (60, 37, 1, 'Sole author'),
       (61, 38, 1, 'Sole author'),
       (62, 39, 1, 'Sole author'),
       (63, 39, 1, 'Sole author'),
       (64, 40, 1, 'Sole author'),
       (65, 41, 1, 'Sole author'),
       (66, 42, 1, 'Sole author'),
       (67, 43, 1, 'Sole author'),
       (68, 44, 1, 'Sole author'),
       (69, 45, 1, 'Sole author'),
       (70, 46, 1, 'Sole author'),
       (71, 47, 1, 'Sole author'),
       (72, 47, 1, 'Sole author'),
       (73, 48, 1, 'Sole author'),
       (74, 49, 1, 'Sole author'),
       (75, 50, 1, 'Sole author'),
       (76, 51, 1, 'Sole author'),
       (77, 52, 1, 'Sole author'),
       (78, 53, 1, 'Sole author'),
       (79, 54, 1, 'Sole author'),
       (80, 55, 1, 'Sole author'),
       (81, 56, 1, 'Sole author'),
       (82, 57, 1, 'Sole author'),
       (83, 58, 1, 'Sole author'),
       (84, 59, 1, 'Sole author'),
       (85, 60, 1, 'Sole author'),
       (86, 61, 1, 'Sole author'),
       (87, 62, 1, 'Sole author'),
       (88, 62, 1, 'Sole author'),
       (89, 63, 1, 'Sole author'),
       (90, 64, 1, 'Sole author'),
       (91, 65, 1, 'Sole author'),
       (92, 66, 1, 'Sole author'),
       (93, 67, 1, 'Sole author'),
       (94, 67, 1, 'Sole author'),
       (95, 68, 1, 'Sole author'),
       (96, 69, 1, 'Sole author'),
       (97, 69, 1, 'Sole author'),
       (98, 70, 1, 'Sole author'),
       (99, 70, 1, 'Sole author'),
       (100, 71, 1, 'Sole author'),
       (101, 72, 1, 'Sole author'),
       (102, 72, 1, 'Sole author'),
       (103, 73, 1, 'Sole author'),
       (104, 74, 1, 'Sole author'),
       (105, 74, 1, 'Sole author'),
       (106, 75, 1, 'Sole author'),
       (107, 75, 1, 'Sole author'),
       (108, 76, 1, 'Sole author'),
       (109, 76, 1, 'Sole author'),
       (110, 76, 1, 'Sole author'),
       (111, 77, 1, 'Sole author'),
       (112, 77, 1, 'Sole author'),
       (113, 78, 1, 'Sole author'),
       (114, 79, 1, 'Sole author'),
       (115, 80, 1, 'Sole author'),
       (116, 81, 1, 'Sole author'),
       (117, 82, 1, 'Sole author'),
       (118, 82, 1, 'Sole author'),
       (119, 83, 1, 'Sole author'),
       (120, 84, 1, 'Sole author'),
       (121, 85, 1, 'Sole author'),
       (122, 86, 1, 'Sole author'),
       (123, 87, 1, 'Sole author'),
       (124, 88, 1, 'Sole author');

INSERT INTO BookGenre (book_id, genre_id)
VALUES (50, 5),
       (50, 7),
       (51, 5),
       (51, 7),
       (52, 2),
       (53, 2),
       (54, 4),
       (55, 15),
       (56, 15),
       (57, 2),
       (58, 2),
       (59, 2),
       (60, 15),
       (61, 21),
       (62, 1),
       (62, 2),
       (63, 2),
       (64, 2),
       (65, 16),
       (66, 11),
       (67, 22),
       (68, 2),
       (69, 7),
       (69, 16),
       (70, 20),
       (71, 2),
       (72, 2),
       (73, 5),
       (74, 4),
       (75, 2),
       (76, 2),
       (77, 20),
       (78, 2),
       (79, 19),
       (80, 2),
       (81, 4),
       (82, 2),
       (83, 2),
       (84, 2),
       (85, 5),
       (86, 4),
       (87, 2),
       (87, 4),
       (88, 2),
       (88, 4),
       (89, 3),
       (90, 2),
       (90, 18),
       (91, 2),
       (91, 10),
       (92, 12),
       (93, 12),
       (94, 12),
       (95, 4),
       (96, 2),
       (96, 4),
       (97, 2),
       (98, 2),
       (99, 2),
       (100, 2),
       (100, 4),
       (101, 6),
       (101, 13),
       (102, 6),
       (102, 13),
       (103, 2),
       (104, 6),
       (104, 1),
       (105, 6),
       (106, 6),
       (107, 7),
       (108, 4),
       (109, 4),
       (110, 4),
       (111, 9),
       (112, 9),
       (113, 17),
       (113, 9),
       (114, 17),
       (114, 9),
       (115, 4),
       (116, 17),
       (117, 7),
       (118, 7),
       (119, 7),
       (119, 16),
       (120, 1),
       (120, 6),
       (121, 2),
       (122, 2),
       (122, 18),
       (123, 2),
       (124, 4);

INSERT INTO Contributor (contributor_name)
VALUES ('Gregory Rabassa'),
       ('Edith Grossman'),
       ('Jay Rubin'),
       ('Philip Gabriel'),
       ('Matthew Ward'),
       ('Constance Garnett'),
       ('Willa Muir'),
       ('William Weaver'),
       ('Lucia Graves'),
       ('Erdag Goknar'),
       ('Margaret Sayers Peden'),
       ('Julie Rose'),
       ('Michael Henry Heim'),
       ('William A. Lyell'),
       ('Terence Brown'),
       ('Andrew Hurley'),
       ('Lysander Kemp'),
       ('W.S. Merwin'),
       ('Edith Pargeter'),
       ('Clare Cavanagh'),
       ('Giovanni Pontiero'),
       ('Richard Zenith'),
       ('Sverre Lyngstad'),
       ('Carl Wildman'),
       ('Tim Wilkinson'),
       ('Carol Brown Janeway'),
       ('Huynh Sanh Thong'),
       ('Deborah Smith'),
       ('Max Lane'),
       ('Gerald Martin'),
       ('D.P. Costello'),
       ('Nicholas de Lange'),
       ('Jessica Cohen'),
       ('Hershel Parker'),
       ('Angela Smith');
INSERT INTO BookContributor (book_id, contributor_id, contributor_type_id, contribution_description)
VALUES (5, 89, 2, 'English translation'),
       (6, 90, 2, 'English translation'),
       (7, 91, 2, 'English translation'),
       (8, 92, 2, 'English translation'),
       (11, 93, 2, 'English translation'),
       (13, 94, 2, 'English translation'),
       (14, 94, 2, 'English translation'),
       (15, 95, 2, 'English translation'),
       (16, 95, 2, 'English translation'),
       (25, 96, 2, 'English translation'),
       (26, 97, 2, 'English translation'),
       (28, 102, 2, 'English translation'),
       (29, 98, 2, 'English translation'),
       (30, 99, 2, 'English translation'),
       (23, 103, 3, 'Editor, Penguin Classics edition'),
       (37, 100, 2, 'English translation'),
       (39, 94, 2, 'English translation'),
       (40, 94, 2, 'English translation'),
       (41, 101, 2, 'English translation'),
       (50, 104, 2, 'English translation'),
       (52, 89, 2, 'English translation'),
       (53, 105, 2, 'English translation'),
       (55, 106, 2, 'English translation'),
       (57, 101, 2, 'English translation'),
       (59, 107, 2, 'English translation'),
       (60, 108, 2, 'English translation'),
       (62, 109, 2, 'English translation'),
       (64, 110, 2, 'English translation'),
       (68, 111, 2, 'English translation'),
       (71, 112, 2, 'English translation'),
       (74, 113, 2, 'English translation'),
       (75, 114, 2, 'English translation'),
       (77, 120, 2, 'English translation'),
       (78, 121, 2, 'English translation'),
       (79, 115, 2, 'English translation'),
       (80, 116, 2, 'English translation'),
       (81, 117, 2, 'English translation'),
       (85, 123, 3, 'Editor, Penguin Classics edition'),
       (89, 118, 2, 'English translation'),
       (91, 119, 2, 'English translation'),
       (92, 122, 3, 'Editor, Norton Critical Edition');
